SELECT "ACCOUNTS"."NAME", "ACCOUNTS"."SALDO", "ACCOUNTS"."OPEN_DATE", "ACCOUNTS"."CLOSE_DATE", "ACCOUNTS"."ACC_NUM" 
FROM "public"."ACCOUNTS", "public"."PRODUCT_TYPE", "public"."PRODUCTS", "public"."CLIENTS"
WHERE "PRODUCTS"."PRODUCT_TYPE_ID" = "PRODUCT_TYPE"."ID"
AND "PRODUCTS"."CLIENT_REF" = "CLIENTS"."ID"
AND "ACCOUNTS"."CLIENT_REF" = "CLIENTS"."ID"
AND "PRODUCT_TYPE"."NAME" = 'ДЕПОЗИТ'

AND "ACCOUNTS"."PRODUCT_REF" = "PRODUCTS"."ID"
AND "PRODUCTS"."PRODUCT_TYPE_ID" = "PRODUCT_TYPE"."ID" 
AND "PRODUCT_TYPE"."NAME" != 'КРЕДИТ'
