SELECT "PRODUCT_TYPE"."NAME", ROUND(AVG("RECORDS"."SUM"), 2) AS MEDIUM_SUMM, "RECORDS"."OPER_DATE" 
FROM "public"."RECORDS", "public"."PRODUCT_TYPE", "public"."ACCOUNTS", "public"."PRODUCTS"
WHERE "RECORDS"."OPER_DATE" = '2021-09-01'
AND "RECORDS"."ACC_REF" = "ACCOUNTS"."ID"
AND "ACCOUNTS"."PRODUCT_REF" = "PRODUCTS"."ID"
AND "PRODUCTS"."PRODUCT_TYPE_ID" = "PRODUCT_TYPE"."ID"
GROUP BY "PRODUCT_TYPE"."NAME", "RECORDS"."OPER_DATE"