SELECT "RECORDS"."OPER_DATE", SUM("RECORDS"."SUM") AS SUM_OPERATION, "CLIENTS"."NAME"
FROM "public"."RECORDS", "public"."CLIENTS", "public"."ACCOUNTS"
WHERE "RECORDS"."ACC_REF" = "ACCOUNTS"."ID"
AND "ACCOUNTS"."CLIENT_REF" = "CLIENTS"."ID"
AND "RECORDS"."OPER_DATE"::date BETWEEN now()::date-interval '1 month' AND now()::date
GROUP BY "RECORDS"."OPER_DATE", "CLIENTS"."NAME"